AD_CAMPAIGN_MINIMAL_DAILY_CREDITS = 1
AD_CAMPAIGN_MINIMAL_CAMPAIGN_DAYS = 1
AD_ACTION_DEPOSIT_MADE = 'deposit_made'
AD_ACTION_DAILY_FEE_CHARGED = 'daily_fee_charged'
AD_ACTION_DEPOSIT_REPLENISHED = 'deposit_replenished'
AD_ACTION_CAMPAIGN_DELETED = 'campaign_deleted'