PAYMENT_METHOD_FREE_PROMO = "free_promo"
PAYMENT_METHOD_PAYPAL = "paypal"
PAYMENT_METHOD_KASPI = "kaspi"
PAYMENT_METHOD_CLOUDPAYMENTS = "cloudpayments"
PAYMENT_METHOD_STARS = "stars"

ALLOWED_PAYMENT_METHODS = [
    PAYMENT_METHOD_FREE_PROMO, PAYMENT_METHOD_PAYPAL, PAYMENT_METHOD_KASPI, PAYMENT_METHOD_CLOUDPAYMENTS, PAYMENT_METHOD_STARS
]

MIN_PAYMENT_FREE_PROMO = 1
MAX_PAYMENT_FREE_PROMO = 10

PAYPAL_MAX_ORDERS_BY_HOUR_FOR_USER = 10
PAYPAL_MINIMAL_PERIOD_FOR_ONE_ORDER = 60 #Seconds

PAYPAL_WEBHOOK_EVENT_CAPTURE_COMPLETED = "PAYMENT.CAPTURE.COMPLETED"
PAYPAL_WEBHOOK_EVENT_ORDER_APPROVED = "CHECKOUT.ORDER.APPROVED"

PAYPAL_WEBHOOK_ALLOWED_EVENTS = [PAYPAL_WEBHOOK_EVENT_ORDER_APPROVED]