# Generated by Django 5.2.7 on 2025-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='User TG_ID')),
                ('tg_firstname', models.CharField(blank=True, default='', max_length=255, verbose_name='User TG_firstname')),
                ('tg_lastname', models.CharField(blank=True, default='', max_length=255, verbose_name='User TG_lastname')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='User TG_username')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Application username')),
                ('mgr_lvl', models.IntegerField(default=0, verbose_name='User mgr level')),
                ('reg_date', models.IntegerField(default=0, verbose_name='User registration date (Unixtime)')),
                ('tg_referer_id', models.BigIntegerField(default=0, verbose_name='Referer TG_ID')),
                ('tg_referer_concatname', models.CharField(blank=True, default='', max_length=255, verbose_name='Referer telegram concated name (firstname + lastname)')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='User interface language (tg)')),
                ('last_activity', models.IntegerField(default=0, verbose_name='User last activity (Unixtime)')),
                ('instance_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Instance ID')),
                ('sid', models.CharField(blank=True, default='', max_length=255, verbose_name='Socket SID')),
                ('credits', models.BigIntegerField(default=0, verbose_name='Coins')),
                ('tab_updates', models.JSONField(blank=True, default=list, verbose_name='Tab updates')),
                ('active', models.BooleanField(default=True)),
                ('business_id', models.IntegerField(default=0, verbose_name='Business ID')),
                ('business_role', models.IntegerField(default=0, verbose_name='Business Role (1 - owner; 2- stuff)')),
                ('contacts_allowed', models.JSONField(blank=True, default=list, verbose_name='Contact list ALLOWED')),
                ('contacts_incoming', models.JSONField(blank=True, default=list, verbose_name='Contact list INCOMING')),
                ('contacts_outcoming', models.JSONField(blank=True, default=list, verbose_name='Contact list OUTCOMING')),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_tg_id', models.BigIntegerField(default=0, verbose_name='User TG_ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Business name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Business description')),
                ('avatar_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Avatar path')),
                ('reg_date', models.IntegerField(default=0, verbose_name='Business registration date (Unixtime)')),
                ('tg_referals', models.JSONField(blank=True, default=list, verbose_name='Referals list')),
                ('staff', models.JSONField(blank=True, default=list, verbose_name='Staff TG IDs')),
                ('active_orders', models.JSONField(blank=True, default=list, verbose_name='Active orders IDs')),
                ('closed_orders', models.JSONField(blank=True, default=list, verbose_name='Closed orders IDs')),
                ('contacts_allowed', models.JSONField(blank=True, default=list, verbose_name='Contact list ALLOWED')),
                ('contacts_incoming', models.JSONField(blank=True, default=list, verbose_name='Contact list INCOMING')),
                ('contacts_outcoming', models.JSONField(blank=True, default=list, verbose_name='Contact list OUTCOMING')),
                ('tariff', models.IntegerField(default=0, verbose_name='Tariff type')),
                ('end_tariff_date', models.IntegerField(default=0, verbose_name='End tariff date (Unixtime)')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_tg_id', models.BigIntegerField(default=0, verbose_name='User TG_ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Business name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Business description')),
                ('avatar_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Avatar path')),
                ('reg_date', models.IntegerField(default=0, verbose_name='Business registration date (Unixtime)')),
                ('tg_referals', models.JSONField(blank=True, default=list, verbose_name='Referals list')),
                ('staff', models.JSONField(blank=True, default=list, verbose_name='Staff TG IDs')),
                ('active_orders', models.JSONField(blank=True, default=list, verbose_name='Active orders IDs')),
                ('closed_orders', models.JSONField(blank=True, default=list, verbose_name='Closed orders IDs')),
                ('contacts_allowed', models.JSONField(blank=True, default=list, verbose_name='Contact list ALLOWED')),
                ('contacts_incoming', models.JSONField(blank=True, default=list, verbose_name='Contact list INCOMING')),
                ('contacts_outcoming', models.JSONField(blank=True, default=list, verbose_name='Contact list OUTCOMING')),
                ('tariff', models.IntegerField(default=0, verbose_name='Tariff type')),
                ('end_tariff_date', models.IntegerField(default=0, verbose_name='End tariff date (Unixtime)')),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
