# Generated by Django 5.2.7 on 2025-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(default=0, verbose_name='Supplier ID')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='User interface language (tg)')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Business name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Business description')),
            ],
            options={
                'db_table': 'customer_translation',
            },
        ),
        migrations.CreateModel(
            name='SupplierTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField(default=0, verbose_name='Supplier ID')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='User interface language (tg)')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Business name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Business description')),
            ],
            options={
                'db_table': 'suppliers_translation',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(default='en', max_length=5, verbose_name='User interface language (tg)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='language',
            field=models.CharField(default='en', max_length=5, verbose_name='User interface language (tg)'),
        ),
    ]
