# Generated by Django 5.2.7 on 2025-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customertranslation_suppliertranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_tg_id', models.BigIntegerField(default=0, verbose_name='User TG_ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Business name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Business description')),
                ('avatar_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Avatar path')),
                ('reg_date', models.IntegerField(default=0, verbose_name='Business registration date (Unixtime)')),
                ('tg_referals', models.JSONField(blank=True, default=list, verbose_name='Referals list')),
                ('staff', models.JSONField(blank=True, default=list, verbose_name='Staff TG IDs')),
                ('active_orders', models.JSONField(blank=True, default=list, verbose_name='Active orders IDs')),
                ('closed_orders', models.JSONField(blank=True, default=list, verbose_name='Closed orders IDs')),
                ('contacts_allowed', models.JSONField(blank=True, default=list, verbose_name='Contact list ALLOWED')),
                ('contacts_incoming', models.JSONField(blank=True, default=list, verbose_name='Contact list INCOMING')),
                ('contacts_outcoming', models.JSONField(blank=True, default=list, verbose_name='Contact list OUTCOMING')),
                ('tariff', models.IntegerField(default=0, verbose_name='Tariff type')),
                ('end_tariff_date', models.IntegerField(default=0, verbose_name='End tariff date (Unixtime)')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='User interface language (tg)')),
            ],
            options={
                'db_table': 'transporters',
            },
        ),
        migrations.CreateModel(
            name='TransporterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_id', models.IntegerField(default=0, verbose_name='Supplier ID')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='User interface language (tg)')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Business name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Business description')),
            ],
            options={
                'db_table': 'transporters_translation',
            },
        ),
    ]
