# Generated by Django 5.2.7 on 2025-12-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transporter_transportertranslation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customertranslation',
            table='customers_translation',
        ),
    ]
