# Generated by Django 5.2.7 on 2025-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customertranslation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='Language label')),
                ('name_english', models.CharField(default='', max_length=255, verbose_name='Language name (English)')),
                ('name_native', models.CharField(default='', max_length=255, verbose_name='Language name (Native)')),
                ('interface', models.JSONField(blank=True, default=dict, verbose_name='Interface data JSON')),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'language_interfaces',
            },
        ),
    ]
