# Generated by Django 5.2.7 on 2025-12-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_languageinterface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='business_role',
        ),
        migrations.AddField(
            model_name='appuser',
            name='active_business_id',
            field=models.IntegerField(default=0, verbose_name='Active_business ID'),
        ),
    ]
