# Generated by Django 5.2.7 on 2025-12-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_appuser_business_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='credits',
        ),
    ]
