# Generated by Django 5.2.7 on 2025-12-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_appuser_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='User App ID')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='User TG_ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('ip_address', models.CharField(blank=True, default='', max_length=255, verbose_name='IP address')),
                ('add_date', models.IntegerField(default=0, verbose_name='Add blacklist date (Unixtime)')),
                ('log', models.JSONField(blank=True, default=list, verbose_name='Activity log')),
            ],
            options={
                'db_table': 'users_blacklist',
            },
        ),
        migrations.CreateModel(
            name='UserGreylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='User App ID')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='User TG_ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('ip_address', models.CharField(blank=True, default='', max_length=255, verbose_name='IP address')),
                ('add_date', models.IntegerField(default=0, verbose_name='Add greylist date (Unixtime)')),
                ('log', models.JSONField(blank=True, default=list, verbose_name='Activity log')),
            ],
            options={
                'db_table': 'users_greylist',
            },
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='mgr_lvl',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='owner_tg_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tg_referals',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='owner_tg_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tg_referals',
        ),
        migrations.RemoveField(
            model_name='transporter',
            name='owner_tg_id',
        ),
        migrations.RemoveField(
            model_name='transporter',
            name='tg_referals',
        ),
        migrations.AddField(
            model_name='appuser',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Settings'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='User TG_ID'),
        ),
    ]
