# Generated by Django 5.2.7 on 2025-12-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userblacklist_usergreylist_remove_appuser_mgr_lvl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='geopoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='geopoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='geopoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporter',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='User ID'),
        ),
    ]
