# Generated by Django 5.2.7 on 2025-12-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customer_geopoint_customer_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='active_business_type',
            field=models.IntegerField(default=0, verbose_name='Active business type'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='active_business_id',
            field=models.IntegerField(default=0, verbose_name='Active business ID'),
        ),
    ]
