# Generated by Django 5.2.7 on 2025-12-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_appuser_active_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.IntegerField(default=1, verbose_name='Business type')),
                ('owner_id', models.IntegerField(default=0, verbose_name='User ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Business name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Business description')),
                ('avatar_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Avatar path')),
                ('reg_date', models.IntegerField(default=0, verbose_name='Business registration date (Unixtime)')),
                ('staff', models.JSONField(blank=True, default=list, verbose_name='Staff TG IDs')),
                ('active_orders', models.JSONField(blank=True, default=list, verbose_name='Active orders IDs')),
                ('closed_orders', models.JSONField(blank=True, default=list, verbose_name='Closed orders IDs')),
                ('contacts_allowed', models.JSONField(blank=True, default=list, verbose_name='Contact list ALLOWED')),
                ('contacts_incoming', models.JSONField(blank=True, default=list, verbose_name='Contact list INCOMING')),
                ('contacts_outcoming', models.JSONField(blank=True, default=list, verbose_name='Contact list OUTCOMING')),
                ('tariff', models.IntegerField(default=0, verbose_name='Tariff type')),
                ('end_tariff_date', models.IntegerField(default=0, verbose_name='End tariff date (Unixtime)')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='User interface language (tg)')),
                ('geopoint', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude')),
                ('timezone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='BusinessTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(default=0, verbose_name='Supplier ID')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='User interface language (tg)')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Business name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Business description')),
            ],
            options={
                'db_table': 'business_translation',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerTranslation',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierTranslation',
        ),
        migrations.DeleteModel(
            name='Transporter',
        ),
        migrations.DeleteModel(
            name='TransporterTranslation',
        ),
    ]
