# Generated by Django 5.2.7 on 2025-12-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_business_businesstranslation_delete_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='active_business_type',
        ),
    ]
