# Generated by Django 5.2.7 on 2025-12-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_appuser_active_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='tg_referer_concatname',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='tg_referer_id',
        ),
        migrations.AddField(
            model_name='appuser',
            name='referrals',
            field=models.JSONField(blank=True, default=list, verbose_name='Referral list'),
        ),
    ]
