# Generated by Django 5.2.7 on 2025-12-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_appuser_tg_referer_concatname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Referral bonus'),
        ),
    ]
