# Generated by Django 5.2.7 on 2025-12-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_appuser_referral_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='referrer_id',
            field=models.IntegerField(default=0, verbose_name='Referer ID'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='referrer_username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Referer app username'),
        ),
    ]
