# Generated by Django 5.2.7 on 2025-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_appuser_referrer_id_appuser_referrer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='business_list',
            field=models.JSONField(blank=True, default=list, verbose_name='Businesses list'),
        ),
        migrations.AlterField(
            model_name='businesstranslation',
            name='business_id',
            field=models.IntegerField(default=0, verbose_name='Business ID'),
        ),
    ]
