# Generated by Django 5.2.7 on 2025-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_appuser_business_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='extra_languages',
            field=models.JSONField(blank=True, default=list, verbose_name='List of language labels'),
        ),
    ]
