# Generated by Django 5.2.7 on 2025-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_business_extra_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='limit_of_business',
            field=models.IntegerField(default=10, verbose_name='Limit of businesses'),
        ),
    ]
