# Generated by Django 5.2.7 on 2025-12-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_apperror'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppError',
        ),
    ]
