# Generated by Django 5.2.7 on 2025-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_apperror'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0, verbose_name='Error date (Unixtime)')),
                ('service', models.CharField(blank=True, default='', max_length=255, verbose_name='Service Name')),
                ('function', models.CharField(blank=True, default='', max_length=255, verbose_name='Function Name')),
                ('error_short', models.CharField(blank=True, default='', max_length=255, verbose_name='Error short description')),
                ('error_text', models.TextField(blank=True, default='', verbose_name='Error description')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Error context')),
            ],
            options={
                'db_table': 'app_error',
            },
        ),
    ]
