# Generated by Django 5.2.7 on 2025-12-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_apperror'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=100),
        ),
    ]
