# Generated by Django 5.2.7 on 2025-12-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_business_currency_alter_business_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='User ID')),
                ('date', models.IntegerField(default=0, verbose_name='Action date (Unixtime)')),
                ('action_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Action type')),
                ('entity_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Entity type')),
                ('entity_id', models.IntegerField(default=0, verbose_name='Entity ID')),
                ('id_address', models.CharField(blank=True, default='', max_length=255, verbose_name='IP address')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Error context')),
            ],
            options={
                'db_table': 'user_action',
            },
        ),
    ]
