# Generated by Django 5.2.7 on 2025-12-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_useraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='id_address',
        ),
    ]
