# Generated by Django 5.2.7 on 2025-12-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_useraction_id_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='IP address'),
        ),
    ]
