# Generated by Django 5.2.7 on 2025-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_useraction_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='businesstranslation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra data'),
        ),
    ]
