# Generated by Django 5.2.7 on 2025-12-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_business_address_businesstranslation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_by_admin', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True, default='', verbose_name='Review ban reason (admin)')),
                ('date', models.IntegerField(default=0, verbose_name='Review date (Unixtime)')),
                ('order_id', models.IntegerField(default=0, verbose_name='Order ID')),
                ('business_id', models.IntegerField(default=0, verbose_name='Rated business ID')),
                ('author_user_id', models.IntegerField(default=0, verbose_name='Author user ID')),
                ('author_business_id', models.IntegerField(default=0, verbose_name='Author business ID')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('rate', models.IntegerField(default=0, verbose_name='Rate 1-5')),
            ],
            options={
                'db_table': 'review_business',
                'constraints': [models.UniqueConstraint(fields=('order_id', 'author_user_id', 'business_id'), name='uniq_review_business_per_order_user')],
            },
        ),
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_by_admin', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True, default='', verbose_name='Review ban reason (admin)')),
                ('date', models.IntegerField(default=0, verbose_name='Review date (Unixtime)')),
                ('product_id', models.IntegerField(default=0, verbose_name='Product ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='Order ID')),
                ('business_id', models.IntegerField(default=0, verbose_name='Rated business ID')),
                ('author_user_id', models.IntegerField(default=0, verbose_name='Author user ID')),
                ('author_business_id', models.IntegerField(default=0, verbose_name='Author business ID')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('rate', models.IntegerField(default=0, verbose_name='Rate 1-5')),
            ],
            options={
                'db_table': 'review_product',
                'constraints': [models.UniqueConstraint(fields=('order_id', 'author_user_id', 'product_id'), name='uniq_review_product_per_order_user')],
            },
        ),
    ]
