# Generated by Django 5.2.7 on 2025-12-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_reviewbusiness_reviewproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='dict_of_username',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dict of usernames'),
        ),
    ]
