# Generated by Django 5.2.7 on 2025-12-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_appuser_dict_of_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='Schedule'),
        ),
    ]
