# Generated by Django 5.2.7 on 2026-01-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_business_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproduct',
            name='reply',
            field=models.TextField(blank=True, default='', verbose_name='Reply'),
        ),
        migrations.AlterField(
            model_name='businesstranslation',
            name='language',
            field=models.CharField(default='en', max_length=5, verbose_name='Business interface language (tg)'),
        ),
    ]
