# Generated by Django 5.2.7 on 2026-01-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_reviewproduct_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewbusiness',
            name='reply',
            field=models.TextField(blank=True, default='', verbose_name='Reply'),
        ),
    ]
