# Generated by Django 5.2.7 on 2026-01-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_reviewbusiness_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='staff_incoming',
            field=models.JSONField(blank=True, default=list, verbose_name='Staff incoming orders'),
        ),
    ]
