# Generated by Django 5.2.7 on 2026-01-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_business_staff_incoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='outcoming_employer_business_id',
            field=models.IntegerField(default=0, verbose_name='Business ID (Potential employer)'),
        ),
    ]
