# Generated by Django 5.2.7 on 2026-01-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_appuser_outcoming_employer_business_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Tariff ID')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Name ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tariff default name')),
                ('active', models.BooleanField(default=False)),
                ('local_names', models.JSONField(blank=True, default=dict, verbose_name='Tariff local names')),
                ('day_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Day cost')),
                ('month_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Month cost')),
                ('year_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Year cost')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Features')),
            ],
            options={
                'db_table': 'tariff_plan',
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='staff',
            field=models.JSONField(blank=True, default=list, verbose_name='Staff IDs'),
        ),
    ]
