# Generated by Django 5.2.7 on 2026-01-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_tariffplan_alter_business_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Default name'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
