# Generated by Django 5.2.7 on 2026-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_business_active_alter_tariffplan_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0, verbose_name='Create date (Unixtime)')),
                ('sender_business', models.IntegerField(default=0, verbose_name='Sender bisiness ID')),
                ('sender_user', models.IntegerField(default=0, verbose_name='Sender user ID')),
                ('receiver_business', models.IntegerField(default=0, verbose_name='Receiver bisiness ID')),
                ('read_users', models.JSONField(blank=True, default=list, verbose_name='Readed users IDs')),
                ('text', models.TextField(blank=True, default='', verbose_name='Text message')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0, verbose_name='Create date (Unixtime)')),
                ('receiver_user', models.IntegerField(default=0, verbose_name='Receiver user ID')),
                ('receiver_business', models.IntegerField(null=True, verbose_name='Receiver bisiness ID')),
                ('type', models.CharField(blank=True, default='', max_length=50, verbose_name='Type of notification')),
                ('is_sapmle', models.BooleanField(default=False)),
                ('sample_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sample code')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text message english (not sampled)')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='Dict of text')),
                ('read_date', models.IntegerField(default=0, verbose_name='Read date (Unixtime)')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
