# Generated by Django 5.2.7 on 2026-01-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sample_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Sample data'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sample_text',
            field=models.TextField(blank=True, null=True, verbose_name='Optional text for sample'),
        ),
    ]
