# Generated by Django 5.2.7 on 2026-01-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_notification_sample_data_notification_sample_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_sapmle',
        ),
    ]
