# Generated by Django 5.2.7 on 2026-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_notification_is_sapmle'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
