# Generated by Django 5.2.7 on 2026-01-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_notification_is_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='tab_updates',
        ),
    ]
