# Generated by Django 5.2.7 on 2026-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_appuser_tab_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='tab_notify',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tab notify'),
        ),
    ]
