# Generated by Django 5.2.7 on 2026-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_appuser_tab_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='outcoming_employer_business_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Business name (Potential employer)'),
        ),
    ]
