# Generated by Django 5.2.7 on 2026-01-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_appuser_outcoming_employer_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='outcoming_last_request',
            field=models.IntegerField(default=0, verbose_name='User last join request (Unixtime)'),
        ),
    ]
