# Generated by Django 5.2.7 on 2026-01-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_appuser_outcoming_last_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='outcoming_last_request',
        ),
        migrations.AddField(
            model_name='appuser',
            name='outcoming_request_delete_date',
            field=models.IntegerField(default=0, verbose_name='User can delete join request (Unixtime)'),
        ),
    ]
