# Generated by Django 5.2.7 on 2026-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_appuser_outcoming_last_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='names_dict_businesses',
            field=models.JSONField(blank=True, default=dict, verbose_name='Businesses dict'),
        ),
        migrations.AddField(
            model_name='message',
            name='names_dict_users',
            field=models.JSONField(blank=True, default=dict, verbose_name='Users dict'),
        ),
        migrations.AddField(
            model_name='message',
            name='order_id',
            field=models.IntegerField(default=0, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver_business',
            field=models.IntegerField(null=True, verbose_name='Receiver bisiness ID (optional)'),
        ),
    ]
