# Generated by Django 5.2.7 on 2026-01-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_message_names_dict_businesses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Stable code, e.g. fruits, dairy', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Default name (EN)', max_length=100)),
                ('dict_names', models.JSONField(blank=True, default=dict, help_text='Localized names, e.g. {"ru": "Фрукты"}')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable code, e.g. kg, l, pcs', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Default full name in English', max_length=100, verbose_name='Full name (EN)')),
                ('name_short', models.CharField(help_text='Default short name in English', max_length=50, verbose_name='Short name (EN)')),
                ('dict_names', models.JSONField(blank=True, default=dict, help_text='Language variants, e.g. {"ru": "килограмм"}', verbose_name='Localized full names')),
                ('dict_names_short', models.JSONField(blank=True, default=dict, help_text='Language variants, e.g. {"ru": "кг"}', verbose_name='Localized short names')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'measures',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(default=0, verbose_name='Business ID (creator)')),
                ('date', models.IntegerField(default=0, verbose_name='Create date (Unixtime)')),
                ('avatar_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Avatar path')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Product name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Product description')),
                ('measure', models.CharField(blank=True, default='', max_length=50, verbose_name='Unit of measure')),
                ('pack_params', models.CharField(blank=True, default='', max_length=255, verbose_name='Pack params decription')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Price for 1 unit of measure')),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=16)),
                ('max_order_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('category_code', models.CharField(blank=True, default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0, verbose_name='Product ID')),
                ('language', models.CharField(default='en', max_length=5, verbose_name='Product interface language (tg)')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Product name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Product description')),
                ('pack_params', models.CharField(blank=True, default='', max_length=255, verbose_name='Pack params decription')),
            ],
            options={
                'db_table': 'product_translation',
            },
        ),
    ]
