# Generated by Django 5.2.7 on 2026-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_category_measure_product_producttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='SKU'),
        ),
    ]
