# Generated by Django 5.2.7 on 2026-01-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measure',
        ),
    ]
