# Generated by Django 5.2.7 on 2026-01-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_remove_product_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unit of measure'),
        ),
    ]
