# Generated by Django 5.2.7 on 2026-01-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_product_measure_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Default name (EN)', max_length=255),
        ),
        migrations.AlterField(
            model_name='measure',
            name='code',
            field=models.CharField(help_text='Stable code, e.g. kg, l, pcs', max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
