# Generated by Django 5.2.7 on 2026-01-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_product_daily_limit_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='system',
            field=models.IntegerField(choices=[(0, 'Both'), (1, 'Metric'), (2, 'Imperial')], default=0, verbose_name='System of measure'),
        ),
        migrations.AddField(
            model_name='measure',
            name='type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Weight'), (2, 'Volume'), (3, 'Length'), (4, 'Count')], default=0, verbose_name='Type of measure'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='dict_names',
            field=models.JSONField(blank=True, default=dict, verbose_name='Localized full names'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='dict_names_short',
            field=models.JSONField(blank=True, default=dict, verbose_name='Localized short names'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full name (EN)'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name_short',
            field=models.CharField(max_length=50, verbose_name='Short name (EN)'),
        ),
    ]
