# Generated by Django 5.2.7 on 2026-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_measure_system_measure_type_alter_measure_dict_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='en', max_length=5, verbose_name='Product primary language'),
        ),
    ]
