# Generated by Django 5.2.7 on 2026-01-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_product_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='favorite_businesses',
            field=models.JSONField(blank=True, default=list, verbose_name='Favorite businesses'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='favorite_products',
            field=models.JSONField(blank=True, default=list, verbose_name='Favorite products'),
        ),
    ]
