# Generated by Django 5.2.7 on 2026-02-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_business_deleted_message_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='individual_customer',
            field=models.BooleanField(default=False),
        ),
    ]
