# Generated by Django 5.2.7 on 2026-02-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_product_individual_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipment_hours',
            field=models.IntegerField(default=0, verbose_name='Average shipment hours'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipment_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Shipment price'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipment_same_day',
            field=models.BooleanField(default=False),
        ),
    ]
