# Generated by Django 5.2.7 on 2026-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_product_shipment_hours_product_shipment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='individual_id',
            field=models.IntegerField(default=0, verbose_name='Individual customer business ID'),
        ),
    ]
