# Generated by Django 5.2.7 on 2026-03-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_appuser_individual_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0, verbose_name='Order date')),
                ('supplier_id', models.IntegerField(default=0, verbose_name='Business ID (supplier)')),
                ('customer_id', models.IntegerField(default=0, verbose_name='Business ID (customer)')),
                ('individual_id', models.IntegerField(default=0, verbose_name='Business ID (individual)')),
                ('delivery_date', models.IntegerField(default=0, verbose_name='Delivery date (Unixtime)')),
                ('status', models.CharField(blank=True, default='', max_length=50, verbose_name='Order status')),
                ('cart', models.JSONField(blank=True, default=list)),
                ('cart_order_date', models.CharField(blank=True, default='', max_length=50, verbose_name='Cart delivery date YYYY-MM-DD')),
                ('customer_comment', models.TextField(blank=True, default='', verbose_name='Reply')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('missed_price', models.BooleanField(default=False)),
                ('update_timeline', models.JSONField(blank=True, default=dict, help_text='Update statuses by Unixtime, e.g. {"1773134918": "created", "1773139923": "live", "1773148923": "completed"}')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='Order ID (supplier)')),
                ('product_id', models.IntegerField(default=0, verbose_name='Product ID (individual)')),
                ('measure_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Unit of measure')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Price for 1 unit of measure')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('confirmed', models.BooleanField(default=False)),
                ('product_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
