# Generated by Django 5.2.7 on 2026-03-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
