# Generated by Django 5.2.7 on 2026-03-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Order status'),
        ),
    ]
