# Generated by Django 5.2.7 on 2026-03-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Avatar path'),
        ),
    ]
