# Generated by Django 5.2.7 on 2026-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_order_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_order_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(default=0, verbose_name='ID (customer)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='individual_id',
            field=models.IntegerField(default=0, verbose_name='ID (individual)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Order name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_id',
            field=models.IntegerField(default=0, verbose_name='ID (supplier)'),
        ),
    ]
