# Generated by Django 5.2.7 on 2026-03-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_order_request_free_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_update',
            field=models.IntegerField(default=0, verbose_name='Last update date'),
        ),
    ]
