# Generated by Django 5.2.7 on 2026-03-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_order_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=100),
        ),
    ]
