# Generated by Django 5.2.7 on 2026-04-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_order_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Avatar path'),
        ),
    ]
