# Generated by Django 5.2.7 on 2026-04-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_message_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='avatar',
        ),
    ]
