# Generated by Django 5.2.7 on 2026-04-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_remove_message_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispute',
            field=models.JSONField(blank=True, default=dict, help_text='dispute detail between suuplier and customer'),
        ),
    ]
