# Generated by Django 5.2.7 on 2026-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_order_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispute_resolved_by_customer_side',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='dispute_resolved_by_supplier_side',
            field=models.BooleanField(default=False),
        ),
    ]
