# Generated by Django 5.2.7 on 2026-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_order_dispute_resolved_by_customer_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rated_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rated_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
