# Generated by Django 5.2.7 on 2026-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_order_rated_customer_order_rated_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='filter_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Filter settings'),
        ),
    ]
