# Generated by Django 5.2.7 on 2026-04-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_business_filter_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='filter_settings',
        ),
    ]
