# Generated by Django 5.2.7 on 2026-05-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_remove_business_filter_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, unique=True, verbose_name='Command')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description (for admin)')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Response data JSON')),
            ],
        ),
        migrations.CreateModel(
            name='BotMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Creating date')),
                ('sending_date', models.IntegerField(default=0, verbose_name='Sending date (UNIX)')),
                ('theme', models.CharField(blank=True, default='', max_length=255, verbose_name='Theme (for admin)')),
                ('userlist', models.JSONField(blank=True, default=list, verbose_name='List of users (TG IDs)')),
                ('message_data', models.JSONField(blank=True, default=dict, verbose_name='Message data JSON')),
                ('confirmed', models.BooleanField(default=False)),
                ('sended', models.BooleanField(default=False)),
                ('not_actual', models.BooleanField(default=False)),
            ],
        ),
    ]
