# Generated by Django 5.2.7 on 2026-05-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_botcommands_botmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotCommands',
        ),
        migrations.DeleteModel(
            name='BotMessages',
        ),
    ]
