# Generated by Django 5.2.7 on 2026-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_botcommands_botmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaignBusinessPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(default=0, verbose_name='Business ID')),
                ('initiator_user_id', models.IntegerField(default=0, verbose_name='Initiator user ID')),
                ('deposit_credits', models.IntegerField(default=0, verbose_name='Deposit credits')),
                ('daily_credits', models.IntegerField(default=0, verbose_name='Daily credits')),
                ('remaining_credits', models.IntegerField(default=0, verbose_name='Remaining credits')),
                ('date_start', models.IntegerField(default=0, verbose_name='Campaign date start')),
                ('date_end', models.IntegerField(default=0, verbose_name='Campaign date end')),
                ('log', models.JSONField(blank=True, default=dict, verbose_name='Campaign log')),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'adcampaignbusinesspromo',
            },
        ),
    ]
