# Generated by Django 5.2.7 on 2026-05-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_adcampaignbusinesspromo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdCampaignBusinessPromo',
        ),
    ]
