# Generated by Django 5.2.7 on 2026-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_adcampaignbusinesspromo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code of payment method (50 symbols max)')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name of payment method')),
                ('name_translations', models.JSONField(blank=True, default=dict, verbose_name='Name translations')),
                ('logo', models.CharField(blank=True, default='', max_length=255, verbose_name='Logo filename')),
                ('currency', models.CharField(blank=True, default='USD', max_length=50)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Merchant ID (Optional)')),
                ('credits_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='App credits per 1 unit of currency')),
                ('custom_options', models.JSONField(blank=True, default=dict, verbose_name='Custom options')),
                ('active', models.BooleanField(default=False)),
                ('show_on_frontend', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
    ]
