# Generated by Django 5.2.7 on 2026-05-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='referrer_payback',
            field=models.BooleanField(default=False),
        ),
    ]
