# Generated by Django 5.2.7 on 2026-05-25 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_paymentmethod_referrer_payback'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='payback_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
