# Generated by Django 5.2.7 on 2026-05-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_paymentmethod_payback_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Payment description'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='description_translations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Description translations'),
        ),
    ]
