# Generated by Django 5.2.7 on 2026-05-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_paymentmethod_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0, verbose_name='Payment date')),
                ('method_code', models.CharField(default='', max_length=50, verbose_name='Code of payment method')),
                ('user_id', models.IntegerField(default=0, verbose_name='User ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(blank=True, default='USD', max_length=50)),
                ('credits_received', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('referrer_id', models.IntegerField(default=0, verbose_name='Referrer user ID')),
                ('credits_payback', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Payment details')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Payments COMFIRMED via API')),
                ('processed', models.BooleanField(default=False, verbose_name='Payment PROCESSED - Credits have been awarded to the user')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
