# Generated by Django 5.2.7 on 2026-05-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Transaction order ID'),
        ),
    ]
