# Generated by Django 5.2.7 on 2026-05-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Payment DELETED'),
        ),
    ]
