# Generated by Django 5.2.7 on 2026-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_payment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('instant', 'Instant'), ('redirect', 'Redirect'), ('sdk', 'SDK')], default='redirect', max_length=50),
        ),
    ]
