# Generated by Django 5.2.7 on 2026-05-28 11:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_paymentmethod_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='max_payment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000'), max_digits=16),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='min_payment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code of method'),
        ),
    ]
