# Generated by Django 5.2.7 on 2026-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_paymentmethod_max_payment_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaignbusinesspromo',
            name='date_next_charge',
            field=models.IntegerField(default=0, verbose_name='Next charge date'),
        ),
    ]
