# Generated by Django 5.2.7 on 2026-06-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_adcampaignbusinesspromo_date_next_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='tariffplan',
            name='tariff_id',
        ),
    ]
