# Generated by Django 5.2.7 on 2026-06-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_remove_business_tariff_remove_tariffplan_tariff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tariff',
            field=models.CharField(default='free', max_length=50, verbose_name='Tariff'),
        ),
    ]
