# Generated by Django 5.2.7 on 2026-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_business_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=255),
        ),
    ]
