# Generated by Django 5.2.7 on 2026-06-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_alter_business_currency_alter_business_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='entity_id',
        ),
    ]
