# Generated by Django 5.2.7 on 2026-06-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_remove_useraction_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='entity_id',
            field=models.BigIntegerField(default=0, verbose_name='Entity ID'),
        ),
    ]
