# Generated by Django 5.2.7 on 2026-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_useraction_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Supplier date'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_ttl',
            field=models.IntegerField(default=0, verbose_name='Supplier TTL'),
        ),
    ]
