# Generated by Django 5.2.7 on 2026-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_order_supplier_date_order_supplier_ttl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0, verbose_name='Action date (Unixtime)')),
                ('service', models.CharField(blank=True, default='', max_length=255, verbose_name='Service Name')),
                ('event', models.CharField(blank=True, default='', max_length=255, verbose_name='Event name')),
                ('status', models.CharField(blank=True, default='', max_length=50, verbose_name='Action status')),
                ('description', models.TextField(blank=True, default='', verbose_name='Action description')),
                ('meta_json', models.JSONField(blank=True, default=dict, verbose_name='Action data')),
                ('duration', models.FloatField(default=0, verbose_name='Action duration (seconds)')),
            ],
            options={
                'db_table': 'system_action',
            },
        ),
    ]
