# Generated by Django 5.2.7 on 2026-06-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_systemaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
    ]
