# Generated by Django 5.2.7 on 2026-06-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_paymentmethod_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcampaignbusinesspromo',
            name='log',
        ),
    ]
