# Generated by Django 5.2.7 on 2026-06-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_remove_adcampaignbusinesspromo_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaignbusinesspromo',
            name='log',
            field=models.JSONField(blank=True, default=list, verbose_name='Campaign log'),
        ),
    ]
