# Generated by Django 5.2.7 on 2026-06-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_adcampaignbusinesspromo_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarPaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0, verbose_name='Payment date')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='User TG_ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Stars amount')),
                ('charge_id', models.CharField(default='', max_length=255, verbose_name='Charghe ID')),
                ('payload', models.CharField(default='', max_length=255, verbose_name='Charghe ID')),
                ('processed', models.BooleanField(default=False, verbose_name='Payment PROCESSED - Credits have been awarded to the user')),
                ('payment_id', models.IntegerField(default=0, verbose_name='Payment ID')),
            ],
            options={
                'db_table': 'star_payment_data',
            },
        ),
    ]
