# Generated by Django 5.2.7 on 2026-06-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_starpaymentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starpaymentdata',
            name='charge_id',
        ),
    ]
