# Generated by Django 5.2.7 on 2026-06-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_remove_starpaymentdata_charge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starpaymentdata',
            name='payment_id',
        ),
    ]
