# Generated by Django 5.2.7 on 2026-06-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_remove_starpaymentdata_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='starpaymentdata',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Charghe ID'),
        ),
        migrations.AddField(
            model_name='starpaymentdata',
            name='payment_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Payment ID'),
        ),
    ]
